$('.owl-carousel').owlCarousel({
    loop:true,
    margin: 10,
    responsiveClass:true,
    responsive:{
        0:{
            items:3,
            nav:false
        },
        600:{
            items:5,
            nav:false
        },
        1000:{
            items:6,
            nav:false,
            loop:true
        }
    }
})